apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dh-ms-ui.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app:  {{ include "dh-ms-ui.name" . }}
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: dh-ms-ui
        tier: backend
        track: stable
    spec:
      containers:
        - name: {{ include "dh-ms-ui.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DBUserName
              valueFrom:
                secretKeyRef:
                  name: pgcred
                  key: DBUserName
            - name: DBPassword
              valueFrom:
                secretKeyRef:
                  name: pgcred
                  key: DBPassword
            - name: DBConnectionString
              valueFrom:
                secretKeyRef:
                  name: pgcred
                  key: DBConnectionString                         
          ports:
            - name: http
              containerPort: 8080
---