steps:
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: sh
   args:
     - '-c'
     - "docker build -f docker/DockerfileFedora-Pro --tag=gcr.io/$PROJECT_ID/deployhub-pro:$COMMIT_SHA --build-arg BLDDATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') --build-arg REPO_NAME=$REPO_NAME --build-arg COMMIT_SHA=$COMMIT_SHA --build-arg GIT_TAG=$(git describe --tags --exact-match || git symbolic-ref -q --short HEAD) ."
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: sh
   args:
     - '-c'
     - "docker build -f docker/DockerfileNginx --tag=gcr.io/$PROJECT_ID/dh-ms-nginx:$COMMIT_SHA --build-arg BLDDATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') --build-arg REPO_NAME=$REPO_NAME --build-arg COMMIT_SHA=$COMMIT_SHA --build-arg GIT_TAG=$(git describe --tags --exact-match || git symbolic-ref -q --short HEAD) ."
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: sh
   args:
     - '-c'
     - "docker build -f docker/DockerGeneral --tag=gcr.io/$PROJECT_ID/dh-ms-general:$COMMIT_SHA --build-arg BLDDATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') --build-arg REPO_NAME=$REPO_NAME --build-arg COMMIT_SHA=$COMMIT_SHA --build-arg GIT_TAG=$(git describe --tags --exact-match || git symbolic-ref -q --short HEAD) ."
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: sh
   args:
     - '-c'
     - "docker build -f docker/DockerUI --tag=gcr.io/$PROJECT_ID/dh-ms-ui:$COMMIT_SHA --build-arg BLDDATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') --build-arg REPO_NAME=$REPO_NAME --build-arg COMMIT_SHA=$COMMIT_SHA --build-arg GIT_TAG=$(git describe --tags --exact-match || git symbolic-ref -q --short HEAD) ."
   
images: 
  - 'gcr.io/$PROJECT_ID/deployhub-pro:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/dh-ms-nginx:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/dh-ms-general:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/dh-ms-ui:$COMMIT_SHA'    


