steps:
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: sh
   args:
     - '-c'
     - "docker build -f DockerfileFedora-Pro --tag=gcr.io/$PROJECT_ID/deployhub-pro:$COMMIT_SHA --build-arg BLDDATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') --build-arg GIT_REPO=$REPO_NAME --build-arg GIT_COMMIT=$COMMIT_SHA --build-arg GIT_TAG=$(git describe --tags --exact-match || git symbolic-ref -q --short HEAD) ."
   dir: docker
images: ['gcr.io/$PROJECT_ID/deployhub-pro:$COMMIT_SHA']
