--- 
# JWT Definition
dh-jwt:
    jwt:
        privatekey: |
            ***REMOVED***
            ***REMOVED***

        publickey: |
            -----BEGIN PUBLIC KEY-----
            -----END PUBLIC KEY-----

# Ingress and SSL Definition
dh-ms-nginx:
    ingress:
        type: ssloff   # sslcert, alb, volumemnt, ssloff  
        alb_certificate_arn: 
        alb_subnets: 
        sslcert:
            chainedcert: | 
                ***REMOVED***
                ***REMOVED***

            privatekkey: |
                ***REMOVED***
                ***REMOVED***

# Database Connection Definition
dh-postgres:
    dbhost: localhost
    dbname: postgres
    dbpass: postgres
    dbport: "5432"
    dbuser: postgres
