--- 
# JWT Definition
dh-jwt:
    jwt:
        privatekey: |
            -----BEGIN PRIVATE KEY-----
            -----END PRIVATE KEY-----

        publickey: |
            -----BEGIN PUBLIC KEY-----
            -----END PUBLIC KEY-----

# Ingress and SSL Definition
dh-ms-nginx:
    ingress:
        type: ssloff   # sslcert, alb, volumemnt, ssloff  
        alb_certificate_arn: 
        alb_subnets: 
        sslcert:
            chainedcert: | 
                -----BEGIN CERTIFICATE-----
                -----END CERTIFICATE-----

            privatekey: |
                -----BEGIN PRIVATE KEY-----
                -----END PRIVATE KEY-----

# Database Connection Definition
dh-postgres:
    dbhost: localhost
    dbname: postgres
    dbpass: postgres
    dbport: "5432"
    dbuser: postgres
