{{ if .Values.SSLChainedCert }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: nginx-secret
data:
  deployhub.com.chained.crt: {{ .Values.SSLChainedCert | b64enc }}
  deployhub.com.key: {{ .Values.SSLPrivateKey | b64enc }}
{{ end }}
