apiVersion: v1
kind: Service
metadata:
  name: {{ include "dh-ms-nginx.name" . }}
spec:
  selector:
    app: {{ include "dh-ms-nginx.name" . }}
    tier: frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
  type: LoadBalancer