apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ include "dh-ms-general.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: dh-ms-general
        tier: backend
        track: stable
    spec:
      containers:
        - name: {{ include "dh-ms-general.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DBUserName
              valueFrom:
                secretKeyRef:
                  name: pgcred
                  key: DBUserName
            - name: DBPassword
              valueFrom:
                secretKeyRef:
                  name: pgcred
                  key: DBPassword
          ports:
            - name: http
              containerPort: 8080
---