apiVersion: v1
kind: Service
metadata:
  name: {{ include "dh-ms-general.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "dh-ms-general.name" . }}
    helm.sh/chart: {{ include "dh-ms-general.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app: {{ include "dh-ms-general.name" . }}
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
